### ISSUE TITLE
Installation fails with civicrm 5.27.1

### ISSUE THREAD

**Issue by mikemazurkiewicz** [civicrm/cv#77] opened 2020-07-31 02:54 UTC
I am trying to install cv on a new system with civicrm 5.27.1. It appears that civicrm install symfony v4.4 and I get the following error messages using composer:

$ composer require civicrm/cv
Using version ^0.3.2 for civicrm/cv
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for civicrm/cv ^0.3.2 -> satisfiable by civicrm/cv[v0.3.2].
    - Conclusion: remove symfony/filesystem v4.4.10
    - Conclusion: don't install symfony/filesystem v4.4.10
    - civicrm/cv v0.3.2 requires symfony/filesystem ~2.8|^3 -> satisfiable by symfony/filesystem.......

**Comment by MikeyMJCO** [comment] 2020-08-27 10:24
Duplicate of #80 open PR at #76 

Unless you're not running Drupal 8 - in which case please let us know which CMS  + Version.

**Comment by totten** [comment] 2020-09-29 06:48
Agree with @MikeyMJCO that this is a duplicate of #76, so closing for that reason.

FWIW, the PHAR-based build of `cv` should avoid conflicts like this. (The canonical codebase here uses some Symfony packages, but when it's published as `cv.phar` the packages are moved into a [private namespace](https://github.com/humbug/php-scoper). `cv.phar` internally uses whatever version of Symfony it wants, and the main project uses whatever version of Symfony that it wants, and they don't conflict.)

As an interim work-around, yyou might consider getting `cv.phar` via [composer-downloads-plugin](https://github.com/civicrm/composer-downloads-plugin) -- that's [how buildkit pulls in cv](https://github.com/civicrm/civicrm-buildkit/blob/998600821c991463536aab21efc5ba338371591e/composer.json#L47).

**Closed by totten** 2020-09-29 06:48 UTC
