### ISSUE TITLE
cv Not found although it is there

### ISSUE THREAD

**Issue by AbdealiJK** [civicrm/cv#1] opened 2016-03-03 14:12 UTC
Hi,

I was trying to run `phpunit` tests on `civicrm` and am facing some issues with `cv`. Note that I am not completely sure whether this is a `cv` issue of whether there is something else that is the problem. (Apologies if this is the wrong place to create the issue)

My system is Ubuntu 14.04 with php `5.5.9-1ubuntu4.14`. I am using apache as a server.
I installed civicrm-buildkit and then went on to use `civibuild` to create a local copy of `dmaster`. In the `dmaster` I wanted to run the phpunit tests. So, I did:

```
ajk:~/buildkit/build/dmaster/sites/all/modules/civicrm$ phpunit
sh: 1: cv: not found
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Command failed (cv php:boot --level=settings):
' in /home/ajk/Documents/civi/civicrm-buildkit/build/dmaster/sites/all/modules/civicrm/tests/phpunit/CiviTest/bootstrap.php:50
Stack trace:
#0 /home/ajk/Documents/civi/civicrm-buildkit/build/dmaster/sites/all/modules/civicrm/tests/phpunit/CiviTest/bootstrap.php(19): cv('php:boot --leve...', 'phpcode')
#1 /home/ajk/Documents/civi/civicrm-buildkit/vendor/phpunit/phpunit/PHPUnit/Util/Fileloader.php(92): include_once('/home/ajk/Docum...')
#2 /home/ajk/Documents/civi/civicrm-buildkit/vendor/phpunit/phpunit/PHPUnit/Util/Fileloader.php(76): PHPUnit_Util_Fileloader::load('/home/ajk/Docum...')
#3 /home/ajk/Documents/civi/civicrm-buildkit/vendor/phpunit/phpunit/PHPUnit/TextUI/Command.php(778): PHPUnit_Util_Fileloader::checkAndLoad('/home/ajk/Docum...')
#4 /home/ajk/Documents/civi/civicrm-buildkit/vendor/phpunit/phpunit/PHPUnit/TextUI/Command.php(606): PHPUnit_TextUI_Command->handleBootstrap('/home/ajk/Docum...')
#5 /home/ in /home/ajk/Documents/civi/civicrm-buildkit/build/dmaster/sites/all/modules/civicrm/tests/phpunit/CiviTest/bootstrap.php on line 50
```

But when I run `cv` locally it works:
```
ajk@ajk-ThinkPad-R60:~/buildkit/build/dmaster/sites/all/modules/civicrm$ cv -V
cv version b6e28d1
ajk@ajk-ThinkPad-R60:~/buildkit/build/dmaster/sites/all/modules/civicrm$ which cv
ajk@ajk-ThinkPad-R60:~/buildkit/build/dmaster/sites/all/modules/civicrm$ 
```
But for some reason `which cv` doesnt work :/

My PATH does have the buildkit/bin
```
ajk@ajk-ThinkPad-R60:~/Documents/civi/civicrm-buildkit/build/dmaster/sites/all/modules/civicrm$ echo $PATH
~/buildkit/bin:/home/ajk/.nvm......etc etc etc
```

and `cv` binary does exist
```
ajk@ajk-ThinkPad-R60:~/Documents/civi/civicrm-buildkit/build/dmaster/sites/all/modules/civicrm$ ls ~/buildkit/bin/ | grep cv
cv
```

**Comment by totten** [comment] 2016-03-03 23:48
* If using standalone phpunit, try `phpunit4` instead of `phpunit`.
 * `cv -V` reports the version but doesn't attempt a bootstrap. It would be interesting to see output from a couple other commands, like:
    * `cv ev "return CRM_Utils_System::version();"`
    * `cv api contact.get id=1`

**Comment by VanagaS** [comment] 2016-09-04 06:42
Could you try this:
sudo curl -LsS https://download.civicrm.org/cv/cv.phar -o /usr/local/bin/cv
sudo chmod +x /usr/local/bin/cv

**Comment by totten** [comment] 2016-10-19 19:05
Cannot reproduce, and no follow-up. 

FWIW, I think there were similar issues in the past when using `Symfony\Process` to spawn subprocesses on Debian-based systems. ([Discussion about the underlying problem and some fixes.](https://github.com/symfony/symfony/issues/18796) However, I don't think that the civix/phpunit/cv arrangement uses this now.

Closing.

**Closed by totten** 2016-10-19 19:05 UTC
